#!/bin/bash

case "$1" in
	start)
		echo "Loading scull, faulty, hello modules"
		scull_load
		module_load faulty
		modprobe hello
		;;
	stop)
		echo "Stopping scull, faulty, hello modules"
		scull_unload
		module_unload faulty
		rmmod hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac